### ISSUE TITLE
/amf3_encode.c:12:40: error：ext/standard/php_smart_str.h：don't has the file

### ISSUE THREAD

**Issue by lingfan** [neoxic/php-amf3#15]
php7.0 don't has this file ext/standard/php_smart_str.h

**Comment by lingfan** [comment]
to modify zend_smart_str.h

can you help to support php7

thx

**Comment by neoxic** [comment]
Well personally, I didn't know this thing even existed. According to php.net, the latest version of PHP is currently 5.6, not even 6.x. I wonder who in the world would use PHP7 beta in production. You must be kidding, right?

**Comment by neoxic** [comment]
PHP-NG support is work in progress now. Stay tuned.

**Comment by neoxic** [comment]
Updated to compile for PHP-NG.
