### ISSUE TITLE
PHP Warning: Undefined symbol: executor_globals_id

### ISSUE THREAD

**Issue by MVLacsap** [neoxic/php-amf3#18]
Trying to include the extension on Centos 7, PHP 7.0.7 running as FPM (Non Thread Safe) gives the following error on startup.

PHP Warning: PHP Startup: Unable to load dynamic library /usr/local/php70/lib/php/extensions/no-debug-non-zts-20151012/amf3.so: undefined symbol: executor_globals_id in Unknown on line 0.

Here's the catch. Web server maintenance is outsourced so i have very little information. Fingers crossed.

**Comment by neoxic** [comment]
Please take a look at this: https://bugs.php.net/bug.php?id=68831

It looks similar and postulates that the "thread-safety" (ZTS) feature for the extension and the PHP version should match.

Please try to compile the extension with ZTS disabled and see what happens.

**Comment by MVLacsap** [comment]
Thanks Arseny,

Came to the same conclusion, this is not PHP-AMF3 related.
