### ISSUE TITLE
Is this extension compatible with PHP 5.6?

### ISSUE THREAD

**Issue by arckid** [neoxic/php-amf3#21]
Hello Neoxic,

I have one old project built on amf-php and PHP 5.6. Can I replace encode and decode functions of amf-php with php-amf3?

Thanks for reading this!
Arckid

**Comment by neoxic** [comment]
It never hurts to try. Don't expect it to be a drop-in replacement though. Some adaptation might be necessary.

You might also need to build an older version of php-amf3 shuffling through Releases. I don't remember which one was suitable for PHP 5.6.

**Comment by arckid** [comment]
Thanks for a quick revert.

Sure, I will try older versions and share the experiment. Will ping you back in case if I need any help further :)

**Comment by ROBERT-MCDOWELL** [comment]
if you need a SSL 1.1.x patched php-5.6 try the one here
https://github.com/ROBERT-MCDOWELL/php
