### ISSUE TITLE
Not able to create amf3.dll. phpize is not supported in windows so please help me to create amf3.dll.

### ISSUE THREAD

**Issue by abrakholiya** [neoxic/php-amf3#22]

**Comment by abrakholiya** [comment]
My PHP version is 5.6.4. I want to change serialize/deserialize functions with amf3_encode/amf3_decode in one of the OLD project to increase the speed of the project. Currently I am testing it in my local windows but not able to create amf3.dll. Please help me. 
Eagerly waiting for the reply.

**Comment by neoxic** [comment]
Hmm... Not sure what I can do to help you except to point out that you will probably need an older version of PHP-AM3 because the master branch currently supports PHP ~7.3 or higher.

**Comment by abrakholiya** [comment]
Thanks for the reply.
That issue is fixed by using the nginx server.

But now the problem is I am not able to covert AMF object to PHP object.
I have tried the following but any of them are not working.

1)
$output = amf3_decode($amf_obj);   // $amf_obj contains the amf object
print_r($output);

2)
$pos = 0;
$nobj = prob(0.5); // prob function is taken from amf3.php test file
$output = amf3_decode($amf_obj, $pos, !$nobj ? AMF3_CLASS_MAP : 0);
print_r($output);

3)
$strs = $amf_obj;
for ($i = 0; $i < count($strs); ++$i) {
       $str = $strs[$i];
       $pos = 0;
       $output = amf3_decode($str, $pos);
       print_r($output);
       if ($pos != strlen($str)) die("Compliance test failed!\n");
}

Please help me to get PHP object.
Following is the AMF object.
[amf_packet.zip](https://github.com/neoxic/php-amf3/files/8025883/amf_packet.zip)
I need following object in $output variable.
[php_object.txt](https://github.com/neoxic/php-amf3/files/8025939/php_object.txt)

**Comment by neoxic** [comment]
Without actual errors/output I am unable to tell where the problem is. I guess you need to learn to make proper bug reports.

**Comment by neoxic** [comment]
As for your `amf_packet.zip`, I can recognize _some_ kind of valid AMF3 starting at offset 0x0000001b. Before that, it doesn't appear to be AMF3.

**Comment by arckid** [comment]
Hello Neoxic,

Thank you for reply.

Let me elaborate little more. We are trying to replace amfphp's amf methods with amf3 extension.

Here is how AMFPHP works basically and what we are trying to do for replacement:

1. PHP request lands to gateway.php which is technically takes the POST raw data and sends it for de-serialisation. After de-serialisation, it takes out a PHP VO and calls the right class::function and then further serialises the return value to AMF3 object and returns back as API response from gateway.php
2. What we are trying to do initially is taking up the POST raw data, writing that to amf_packet.amf and trying to decode with amf3_decode to get the PHP VO.

At this level, we are not able to decode it. I am sure we are doing very silly mistake here but kindly help us to identify that.

Coming back to your suggestion of some kind of valid AMF at 0x0000001b, We've removed the first byte and now amf3_decode returns 1 but no change in the input string.

Kindly guide us and once again, thank you for your response and help.
