### ISSUE TITLE
error msg AMFSerializable not found

### ISSUE THREAD

**Issue by robo-loki** [neoxic/php-amf3#24]
Hi-

I got anonymous object literals working and can receive an array using apache royale code.
When I try to fool with the Serializable object, it give me this error:

interface AMF3Serializable not found. PhP error is looking in my actionscript directory.

I put the header amf3.h in my include_path. Can I please have a hint as to how to fix this?

THANKS,
robo-loki

**Comment by robo-loki** [comment]
Hi,

I included this email before I sent the video. I am trying to create videos to make it easier for apache royale people to do things. If people can get up to speed faster on using the tools, it helps with apache royale.
--------------------------------email msg. body--------------------------------------------------------------------------
Hi all-

I am going to share a google drive video shortly to help the windows users check out php_amf3.

Two quick things to note:

1. For cygwin, I said in the video I shut down my virus shield (you can add an exception instead of shutting down the whole AV shield, or it just may work on your AV).
2.) Also, if you do want to check it out, I recommend abyss webserver. I can show you how to trick out your abyss web server settings that will help you. I could put out an abyss webserver video if you'd like.

Well, anyways... we might actually be spoilt for choices here. I know people use amfphp by silex labs, and if you like that better and want to keep on using silex, that is cool.

I'm still testing php_amf3 in windows. So far, I can pass associative arrays and anonymous object literals from PhP. I am trying to get into using one more feature, and I posted a question to support for php_amf3.

thanks,
jim (robo-loki)

**Comment by neoxic** [comment]
Hi Jim,

> interface AMF3Serializable not found. PhP error is looking in my actionscript directory.
For the `AMF3Serializable` interface to be available, you need to make sure you are using the latest PHP-AMF3 release (php-amf3-2.1.1 for the time being). Not sure what you mean by "actionscript directory" though.

> I put the header amf3.h in my include_path. Can I please have a hint as to how to fix this?
Umm... Once your php-amf3 extension has been compiled, you no longer need its source code, so I guess I don't really understand what you mean by "including amf3.h in include_path".

In order for me to reproduce the problem you're facing, please provide:
1) a piece of PHP code that is not working;
2) your php-amf3 version;
3) error output and other related info.

**Comment by robo-loki** [comment]
Hi -

I had some success working on this about 30 minutes ago. 

Here is the code:

`<?php
interface AMF3Serializable {}
class MyClass implements AMF3Serializable {
    public  $baseball;
    public  $basketball;

    public function __construct($b1, $b2) {
        $this->baseball=$b1;
        $this->basketball=$b2;
        $this->__toAMF3;
    }
    public function __toAMF3() {
        return [
            'baseball' => $this->baseball,
            'basketball' => $this->basketball,
        ];
    }
}

class_implements('MyClass');
$begin = '<body>';
$end1 = '</body>';
$obj= new MyClass("sox", "celtics");
$obj->__construct("sox", "celtics");
echo $obj->__toAMF3() ;

?>
That seems to return an array now. I guess I can receive it on the other side. I wish I could get it to go as anonymous object instead of array, but that will give me something to do, and I will have indexed array capability . I set up parsing for the anonymous object and associative array that use amf3_encode($data, AMF3_FORCE_OBJECT); I will check if I can make the array anonymous inside the class up above in case someone wants that. I am still learning PHP_AMF3.

Come to think of it, I might be able to tweak that return  statement in PhP for the sample serializable listed on your github page to make it go anonymous. 

This is a very cool github project.

THANKS for helping,
jim

**Comment by neoxic** [comment]
```
interface AMF3Serializable {}
```
You don't need to declare this interface because it's declared internally when the extension is loaded. Since you do declare it, I assume your PHP-AMF3 version is older than 2.1 because otherwise PHP wouldn't allow you to redefine it. Again, make sure your PHP-AMF3 version 2.1 or higher. Otherwise, `AMF3Serializable` will not work for you.

```
$obj= new MyClass("sox", "celtics");
$obj->__construct("sox", "celtics");
```
The second line is superfluous.

```
echo $obj->__toAMF3() ;
```
You don't call `__toAMF3()` directly. It's called indirectly within `am3_encode()`. Please refer to README for more details.

**Comment by neoxic** [comment]
> I wish I could get it to go as anonymous object instead of array, but that will give me something to do, and I will have indexed array capability . I set up parsing for the anonymous object and associative array that use amf3_encode($data, AMF3_FORCE_OBJECT); I will check if I can make the array anonymous inside the class up above in case someone wants that. I am still learning PHP_AMF3.

Simply pass `AMF3_FORCE_OBJECT` as flags to `amf3_encode()` if you want all non-indexed (associative) arrays to be represented as anonymous objects.

**Comment by robo-loki** [comment]
Thanks very much for the help. I have been running the PhP test code. It is working really cool. If I leave off the amf3_encode and do this in the __toAMF3: 
` $data= [
            'baseball' => $this->baseball,
            'basketball' => $this->basketball,
               ];

       $result = $begin . $data . $end1;
       echo $result;
    }

I get an indexed array.

If I do this:

` $data= array (
            'baseball' => $this->baseball,
            'basketball' => $this->basketball,
        );

       $result = $begin . json_encode($data) . $end1;
       echo $result;

I get an object.`


I will check out all of your notes!
have a very cool week.
THANKS,
jim
