### ISSUE TITLE
comment on php-amf3 docker

### ISSUE THREAD

**Issue by jmcnamara10001** [neoxic/php-amf3#26]
Hi Neoxic-

I couldnt use cygwin to build php extension for windows. So I am using windows with docker to put linux on my machine. I am not very good at docker yet but i did get it to build an amf3.so etc.

I think that is  a cool road to go for people that lost cygwin on windows. When i get further down the road if you arent already using docker i will try to share something about my docker-compose.yaml file and Dockerfile. thanks -jim

**Comment by neoxic** [comment]
I'm not sure what you mean by "people lost cygwin on windows". CygWin is still alive and thriving although it doesn't support 32-bit Windows anymore which is quite expected. Furthermore, you can always use WSL on Windows instead. Check this out as a reference:
https://github.com/adrianblakey/slot-car-ecom/wiki/The-ESCape32-Firmware#building-the-sources-on-windows

**Comment by jmcnamara10001** [comment]
Okay this is now closed. That is a pretty cool way to install php-amf3. Id rather use this way (WSL and cmake) or docker for installing PhP-Amf3 anyway but some people may like cygwin. I looked and maybe by mistake a while ago though there is no PhP support.  Someone probably maintains support for PhP now at that project. (cygwin) Sorry. Thanks for the cool tips. jim
